version: 1.0.{build}
build:
  verbosity: minimal
install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake olam.pro
  - mingw32-make
after_build:
  - windeployqt --compiler-runtime --release release/olam.exe
  - cp C:\\Qt\\5.10.1\\mingw53_32\\bin\\libwinpthread-1.dll release
  - cp -r db release
  - cp -r misc release
  - cp LICENSE release
  - iscc olam.iss
artifacts:
  - path: release
    type: zip
  - path: Output\olam-*.exe
