name: olam  # the name of the snap
version: 0.1  # the version of the snap
summary: This is my-snap's summary  # 79 char long summary
description: This is my-snap's description  # a longer description for the snap
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
  olam:
    command: desktop-launch olam
    plugs:
      - x11
      - home

parts:
    olam:
        source: /home/tachyons/projects/olam
        plugin: qmake
        qt-version: qt5
        build-packages:
          - qttools5-dev
          - build-essential
          - qttools5-dev-tools
        after: [desktop/qt5]
    env:
      plugin: nil
      stage-packages:
        - libqt5gui5
        - libqt5sql5
        - libqt5sql5-sqlite
        - libqt5widgets5
        - libqt5xml5
      after: [qt5conf]
