name: olam  # the name of the snap
version: 1.2  # the version of the snap
summary: Olam English Malayalam Dictionary   # 79 char long summary
description: Unofficial Olam desktop client for ubuntu # a longer description for the snap
confinement: strict  # use "strict" to enforce system access only via declared interfaces

apps:
  olam:
    command: desktop-launch $SNAP/bin/olam
    plugs:
     - unity7
     - desktop
     - desktop-legacy
     - wayland
     - home
     - x11
     - network
     - network-bind
     - opengl

parts:
    olam:
        source: .
        #source: https://github.com/tachyons/olam.git
        plugin: qmake
        qt-version: qt5
        build-packages:
          - qt5-default
          - qttools5-dev
          - build-essential
          - qttools5-dev-tools
        stage-packages:
          - libqt5core5a
          - libqt5gui5
          - libqt5widgets5
          - libqt5dbus5
          - libqt5svg5
          - libreadline6
          - libcanberra-gtk-module
          - liblua5.2-0
          - ttf-ubuntu-font-family
          - fonts-dejavu
          - libqt5sql5
          - libqt5sql5-sqlite
        after: [desktop-qt5]
